---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-refbox
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /refbox/?(.*)
            pathType: Prefix
            backend:
              service:
                name: refbox-frontend-service
                port:
                  number: 80
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: refbox-gui-service
                port:
                  number: 1234
          - path: /mqtt-ws/
            pathType: Prefix
            backend:
              service:
                name: mqtt-service
                port:
                  number: 1884
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simulator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    #nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /simulator/api/(.*)
            pathType: Prefix
            backend:
              service:
                name: simulator-backend-service
                port:
                  number: 8000
          - path: /simulator/(.*)
            pathType: Prefix
            backend:
              service:
                name: simulator-frontend-service
                port:
                  number: 4200