apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883
    protocol mqtt
    listener 1884
    protocol websockets
    allow_anonymous true
    #cafile is for certificate authority. Most likely not needed with non-self signed CA.
    #cafile /certs/ca/ca.crt
    #certfile /certs/crt/tls.crt
    #keyfile /certs/crt/tls.key
    #require_certificate false
    #tls_version tlsv1.2
    #stdout so that we see in on K8S.
    log_dest stdout
    #log_dest file /mosquitto/log/mosquitto.log
    log_timestamp_format %Y-%m-%dT%H:%M:%S
