{{if .Values.cyan}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ps-cyan
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.cyan.imagePullSecret | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyan
  labels:
    app: cyan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyan
  template:
    metadata:
      labels:
        app: cyan
    spec:
      imagePullSecrets:
        - name: ps-cyan
      containers:
{{- range $container := .Values.cyan.containers }}
        - name: {{ $container.name }}
          image: {{ $container.image }}
          imagePullPolicy: Always
          env:
{{- range $envEntry := $container.env }}
            - name: {{ $envEntry.name }}
              value: {{ $envEntry.value }}
{{end}}
{{ if $container.ports}}
          ports:
{{- range $port := $container.ports }}
           - containerPort: {{$port.port}}
{{end}}
{{end}}

{{end}}
---
apiVersion: v1
kind: Service
metadata:
  name: cyan-team
spec:
  selector:
    app: cyan
  ports:
{{- range $container := .Values.cyan.containers }}
{{ if $container.ports}}
{{- range $port := $container.ports }}
    - protocol: {{ $port.protocol }}
      name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
{{end}}
{{end}}
{{end}}
{{end}}