---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sim-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /sim-controller/?(.*)
            pathType: Prefix
            backend:
              service:
                name: sim-controller
                port:
                  number: 5000